# Generated by Django 3.1.3 on 2020-11-11 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoEmpresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomempresa', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(default=0)),
                ('nombre_representante', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechatermino', models.DateField()),
                ('valormensual', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoProyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomempresa', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(default=0)),
                ('nombre_representante', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('fechainicio', models.DateField()),
                ('fechatermino', models.DateField()),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('tipo_proyecto', models.CharField(max_length=50)),
                ('valor_proyecto', models.IntegerField(default=0)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
    ]
